#!/bin/bash

QFST_PSN_SESI2="
STSN1122_BIOLOGI~SINARAN
STSN1142_MAKMAL~KEDARIOAKTIFAN~DAN~SINARAN
STSN2022_PERALATAN~NUKLEAR~DAN~TEKNOLOGI~REAKTOR
STSN2062_MAKMAL~PEMPROSESAN~SINARAN
STSN2082_TEKNOLOGI~NUKLEAR~DALAM~INDUSTRI
STSN2142_FIZIK~NUKLEAR
STSN2162_FIZIK~KESIHATAN
STSN3022_KIMIA~INDUSTRI~NUKLEAR~KIMIA~INDUSTRI~NUKLEAR
STSN3042_TEKNIK~NUKLEAR~DALAM~PERUBATAN
STSN3062_KESELAMATAN~INDUSTRI
STSN3182_SISTEM~PENGURUSAN~KESELAMATAN~SINARAN
STSN3663_TEKNIK~NUKLEAR~DALAM~KEHIDUPAN
STSN3992_LATIHAN~ILMIAH~I
STSN4996_LATIHAN~ILMIAH~II
STSN4889_LATIHAN~INDUSTRI
"

QFST_PKSN_SESI2="
STSN6052_CAMPURTANGAN~BAGI~PERLINDUNGAN~AWAM
STSN6142_KEJURUTERAAN~SEKITARAN~REAKTOR~NUKLEAR
STSN6222_PENILAIAN~DEDAHAN~DALAMAN
STSN6322_KESELAMATAN~NUKLEAR~SEKURITI~DAN~KAWAL~GUNAAN
STSN6412_PENGURUSAN~SISA~RADIOAKTIF
STSN6512_DEDAHAN~DALAM~PERUBATAN
STSN6522_PERLINDUNGAN~TERHADAP~DEDAHAN~PEKERJAAN
STSN6624_AMALI~II
STSN6986_PROJEK~PENYELIDIKAN~II
"

QFST_PKSN_3S_SESI2="
STSN6113_Kegunaan~Sekuriti~dan~Kawalgunaan~Nuklear
STSN6193_Perlindungan~Fizikal~ke~atas~Bahan~Nuklear~dan~Fasiliti~Nuklear
STSN6182_Kawalan~dan~Perakaunan~Bahan~Nuklear~untuk~Tujuan~Kawalgunaan~dan~Sekuriti
STSN6183_Forensik~Nuklear
STSN6342_Kesiapsiagaan~dan~Tindakbalas~Kecemasan~Nuklear
STSN6282_Pengurusan~Sekuriti~Nuklear
STSN6382_Amali~II
STSN6283_Sekuriti~Nuklear~bagi~Bahan~Di~Luar~Kawalan~Perundangan
STSN6972_Projek~Penyelidikan~I
STSN6976_Projek~Penyelidikan~II
"

FOLDER="
1.PROFIL~KURSUS-NAMA~PENSYARAH-SINOPSIS-RUJUKAN-HPK-RANCANGAN~PENGAJARAN-PELAN~PENILAIAN
2.SOALAN~PEPERIKSAAN~AKHIR~DAN~SKEMA~(DENGAN~KATA~LALUAN)
3.LAIN-LAIN~UJIAN-TUGASAN-KUIZ-RUBRIK~PEMARKAHAN
4.MARKAH~MENTAH
5.GRED
6.BORANG~MODERASI~SOALAN~KURSUS~DAN~DERAF~SOALAN~(DGN~KATA~LALUAN)
"

for isubject in $QFST_PSN_SESI2
do
    for jfolder in $FOLDER
    do
	folder_path="./${isubject}/${jfolder}"
	folder_path="${folder_path//\~/ }"
	echo "$folder_path"
	mkdir -p "$folder_path"
    done
done
